name: neuralflight
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  camera: ^0.10.5+8
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  path: ^1.8.3
  path_provider: ^2.1.1

flutter_launcher_icons:
  image_path: "assets/icons/appicon.jpg"
  android: true
  ios: true
  min_android_sdk: 21
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  fonts:
    - family: DM Sans
      fonts:
        - asset: assets/fonts/DMSans-VariableFont_opsz,wght.ttf
  uses-material-design: true